### PR TITLE
Update setup.py since the lib doesn't support numpy 2.0

### PR DESCRIPTION
**Pull request by DanyilVoloshchuk**
the lib is causing AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64`

### CODE REVIEW

**Comment by DanyilVoloshchuk** [comment]
I guess it will be even more simple if u just create a 1.73 version without np.float_ and numpy 2.0😅

**Comment by brianjbuck** [comment]
@DanyilVoloshchuk, is this causing your builds to fail? If not, I'd rather find a more complete solution than limiting to `numpy<=2.0`

**Comment by DanyilVoloshchuk** [comment]
@brianjbuck Unfortunately, yes, it is causing my builds to fail:(
but If U don't mind, I can change PR to one that removes numpy.float_ from encoders or adds it only if the version on numpy is lower then 2.0, what would u prefer?

**Comment by brianjbuck** [comment]
@DanyilVoloshchuk, That would be a better solution than the original one proposed. You really shouldn't need it however since v3.3 `orjson` supports both numpy versions out of the box. That encoder was written before `orjson` supported `numpy` and [only exists for some backwards compatibility before everyone upgraded `orjson` versions](https://github.com/brianjbuck/drf_orjson_renderer?tab=readme-ov-file#numpy). 

My preferred solution would be to remove the  `DjangoNumpyJSONEncoder` entirely and have everyone migrate away from using that encoder. The docs could probably be more clear that developers should be using the `orjson` options instead:

```Python
REST_FRAMEWORK = {
    "ORJSON_RENDERER_OPTIONS": (
        orjson.OPT_SERIALIZE_NUMPY,
    ),
}
```

**Pull request closed without merging**
